### ISSUE TITLE
Tried to build project as a Java client and got  HTTP 400 error 

### ISSUE THREAD

**Issue by miko-code** [x1ddos/go-tictactoe#5]
I tried to build your app as a Java  client and got this error 

```
mik@mik-Aspire-S3:~/go-programs$ URL='https://go-endpoints.appspot.com/tictactoe'
mik@mik-Aspire-S3:~/go-programs$ curl -s $URL > tic_testmik@mik-Aspire-S3:~/go-programs$ $HOME/go_appengine/endpointscfg.py gen_client_lib java tic_test
Traceback (most recent call last):
  File "/home/mik/go_appengine/endpointscfg.py", line 133, in <module>
    run_file(__file__, globals())
  File "/home/mik/go_appengine/endpointscfg.py", line 129, in run_file
    execfile(_PATHS.script_file(script_name), globals_)
  File "/home/mik/go_appengine/google/appengine/tools/endpointscfg.py", line 561, in <module>
    main(sys.argv)
  File "/home/mik/go_appengine/google/appengine/tools/endpointscfg.py", line 557, in main
    args.callback(args)
  File "/home/mik/go_appengine/google/appengine/tools/endpointscfg.py", line 458, in _GenClientLibCallback
    args.build_system)
  File "/home/mik/go_appengine/google/appengine/tools/endpointscfg.py", line 335, in _GenClientLib
    build_system, client_name)
  File "/home/mik/go_appengine/google/appengine/tools/endpointscfg.py", line 366, in _GenClientLibFromContents
    raise ServerRequestException(error)
__main__.ServerRequestException: HTTP 400 (Bad Request) error when communicating with URL: https://google-api-client-libraries.appspot.com/generate.  Details: ill-formed JSON: No JSON object could be decoded
```

**Comment by x1ddos** [comment]
That URL is just an HTML page with TicTacToe game.
You probably want https://go-endpoints.appspot.com/_ah/api/discovery/v1/apis/tictactoe/v1/rpc or https://go-endpoints.appspot.com/_ah/api/discovery/v1/apis/tictactoe/v1/rest  to generate a client lib.

**Comment by miko-code** [comment]
Hey ,
this is working good 
     https://winged-precept-864.appspot.com/_ah/api/ballota/v2/getuser2
but  on   those links im getting 404   what am im missing 
https://winged-precept-864.appspot.com/_ah/api/discovery/v1/apis/ballota/v1/rest
https://winged-precept-864.appspot.com/_ah/api/discovery/v1/apis/ballota/v1/rpc
